// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfM2rorPtElZZsuLxEFAzIdhHfb96ccKQ',
    appId: '1:96597404835:web:d445a60d812564423e2316',
    messagingSenderId: '96597404835',
    projectId: 'nagarathar-3d13e',
    authDomain: 'nagarathar-3d13e.firebaseapp.com',
    storageBucket: 'nagarathar-3d13e.appspot.com',
    measurementId: 'G-LGZCE16JHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAAihcqv6K3usrBFRcwv9daeHUJdMS0Hs',
    appId: '1:96597404835:android:84489cc8b5e294323e2316',
    messagingSenderId: '96597404835',
    projectId: 'nagarathar-3d13e',
    storageBucket: 'nagarathar-3d13e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOCdHBTcwJorHF0aiakAux54R5nSiPi1E',
    appId: '1:96597404835:ios:d8ee6bad3a52f5473e2316',
    messagingSenderId: '96597404835',
    projectId: 'nagarathar-3d13e',
    storageBucket: 'nagarathar-3d13e.appspot.com',
    iosBundleId: 'com.skandasoft.nagarathar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOCdHBTcwJorHF0aiakAux54R5nSiPi1E',
    appId: '1:96597404835:ios:d8ee6bad3a52f5473e2316',
    messagingSenderId: '96597404835',
    projectId: 'nagarathar-3d13e',
    storageBucket: 'nagarathar-3d13e.appspot.com',
    iosBundleId: 'com.skandasoft.nagarathar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfM2rorPtElZZsuLxEFAzIdhHfb96ccKQ',
    appId: '1:96597404835:web:3fc6d26adb41229b3e2316',
    messagingSenderId: '96597404835',
    projectId: 'nagarathar-3d13e',
    authDomain: 'nagarathar-3d13e.firebaseapp.com',
    storageBucket: 'nagarathar-3d13e.appspot.com',
    measurementId: 'G-XF6C6TSZT8',
  );
}
